version: "3.8"

services:
    laravel-frontend:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-frontend
        container_name: laravel-frontend
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost:8000
            - LOG_CHANNEL=stdout
        restart: unless-stopped
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
