version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-frontend
    container_name: laravel-frontend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=sqlite
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge